[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0"
openssl = { version = "0.10" }
tokio = { version = "1.0", features = ["full"] }
rand = "0.8.4"